INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Alaska', 'AK',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Alabama', 'AL',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Arkansas', 'AR',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Arizona', 'AZ',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('California', 'CA',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Colorado', 'CO',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Connecticut', 'CT',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('District of Columbia', 'DC',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Delaware', 'DE',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Florida', 'FL',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Georgia', 'GA',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Hawaii', 'HI',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Iowa', 'IA',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Idaho', 'ID',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Virginia', 'VA',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Vermont', 'VT',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Washington', 'WA',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Wisconsin', 'WI',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('West Virginia', 'WV',1);
INSERT INTO [dbo].[State] ([Name],[Abbreviation],[IsPrimaryState]) VALUES ('Wyoming', 'WY',1);